### ISSUE TITLE
Add Desktop tools

### ISSUE THREAD

**Issue by HinataKato** [ogtega/steamauth#1]
This application is beautiful, but without a desktop tool, can you add one?

**Comment by ogtega** [comment]
I'm no longer working on this application, I feel like flutter needs to mature. I'm currently adding multi-platform authentication in [GhostOTP](https://github.com/ogtega/ghostotp).

**Comment by HinataKato** [comment]
> I'm no longer working on this application, I feel like flutter needs to mature. I'm currently adding multi-platform authentication in [GhostOTP](https://github.com/ogtega/ghostotp).

okay, thank you.
